[book]
title = "My Project Documentation"
author = "Your Name"
description = "This is the documentation for my project."

[output.html]
default-theme = "light"

[preprocessor.multilang]
language-table = { "zh" = "中文", "en" = "English" }
